"""Catalog of 100 popular German nouns for seed migration."""

from __future__ import annotations

# Each entry: (singular, plural, article_sg, article_pl, definition_de)
# article_sg/pl: der | die | das | die (plural article is usually die)
GERMAN_NOUNS_CATALOG: list[tuple[str, str, str, str, str]] = [
    ("Haus", "Häuser", "das", "die", "Gebäude zum Wohnen."),
    ("Mann", "Männer", "der", "die", "Erwachsener männlicher Mensch."),
    ("Frau", "Frauen", "die", "die", "Erwachsene weibliche Person."),
    ("Kind", "Kinder", "das", "die", "Junger Mensch."),
    ("Tag", "Tage", "der", "die", "Zeiteinheit von 24 Stunden."),
    ("Nacht", "Nächte", "die", "die", "Dunkle Tageszeit zum Schlafen."),
    ("Wasser", "—", "das", "—", "Flüssigkeit zum Trinken."),
    ("Brot", "Brote", "das", "die", "Grundnahrungsmittel aus Mehl."),
    ("Apfel", "Äpfel", "der", "die", "Runde Frucht."),
    ("Milch", "—", "die", "—", "Weiße Flüssigkeit von Kühen."),
    ("Stadt", "Städte", "die", "die", "Große Siedlung."),
    ("Land", "Länder", "das", "die", "Staat oder ländliches Gebiet."),
    ("Schule", "Schulen", "die", "die", "Ort zum Lernen."),
    ("Arbeit", "Arbeiten", "die", "die", "Tätigkeit zum Geldverdienen."),
    ("Zeit", "Zeiten", "die", "die", "Dauer oder Moment."),
    ("Jahr", "Jahre", "das", "die", "Zeitraum von zwölf Monaten."),
    ("Monat", "Monate", "der", "die", "Teil eines Jahres."),
    ("Woche", "Wochen", "die", "die", "Sieben Tage."),
    ("Freund", "Freunde", "der", "die", "Nahestehende Person."),
    ("Familie", "Familien", "die", "die", "Verwandte im Haushalt."),
    ("Name", "Namen", "der", "die", "Bezeichnung einer Person."),
    ("Hand", "Hände", "die", "die", "Körperteil zum Greifen."),
    ("Auge", "Augen", "das", "die", "Sinnesorgan zum Sehen."),
    ("Kopf", "Köpfe", "der", "die", "Oberer Teil des Körpers."),
    ("Herz", "Herzen", "das", "die", "Organ für Gefühle und Blut."),
    ("Buch", "Bücher", "das", "die", "Gedruckte oder digitale Lektüre."),
    ("Tisch", "Tische", "der", "die", "Möbelstück mit Platte."),
    ("Stuhl", "Stühle", "der", "die", "Sitzmöbel."),
    ("Tür", "Türen", "die", "die", "Öffnung in einer Wand."),
    ("Fenster", "Fenster", "das", "die", "Glasöffnung für Licht."),
    ("Auto", "Autos", "das", "die", "Fahrzeug mit Motor."),
    ("Zug", "Züge", "der", "die", "Schienenfahrzeug."),
    ("Bus", "Busse", "der", "die", "Öffentliches Straßenfahrzeug."),
    ("Flugzeug", "Flugzeuge", "das", "die", "Luftfahrzeug."),
    ("Straße", "Straßen", "die", "die", "Weg für Verkehr."),
    ("Park", "Parks", "der", "die", "Grüne Erholungsfläche."),
    ("Garten", "Gärten", "der", "die", "Grundstück mit Pflanzen."),
    ("Baum", "Bäume", "der", "die", "Große Pflanze mit Stamm."),
    ("Blume", "Blumen", "die", "die", "Bunte Pflanze."),
    ("Hund", "Hunde", "der", "die", "Haustier, oft treuer Begleiter."),
    ("Katze", "Katzen", "die", "die", "Kleines Haustier."),
    ("Vogel", "Vögel", "der", "die", "Tier mit Federn."),
    ("Fisch", "Fische", "der", "die", "Tier im Wasser."),
    ("Geld", "—", "das", "—", "Mittel zum Bezahlen."),
    ("Preis", "Preise", "der", "die", "Kosten eines Produkts."),
    ("Geschäft", "Geschäfte", "das", "die", "Laden zum Einkaufen."),
    ("Markt", "Märkte", "der", "die", "Ort zum Verkauf."),
    ("Restaurant", "Restaurants", "das", "die", "Ort zum Essen gehen."),
    ("Hotel", "Hotels", "das", "die", "Unterkunft für Reisende."),
    ("Zimmer", "Zimmer", "das", "die", "Raum in einer Wohnung."),
    ("Bett", "Betten", "das", "die", "Möbel zum Schlafen."),
    ("Küche", "Küchen", "die", "die", "Raum zum Kochen."),
    ("Bad", "Bäder", "das", "die", "Raum zum Waschen."),
    ("Telefon", "Telefone", "das", "die", "Gerät zum Telefonieren."),
    ("Computer", "Computer", "der", "die", "Elektronisches Gerät."),
    ("Internet", "—", "das", "—", "Weltweites Datennetz."),
    ("Sprache", "Sprachen", "die", "die", "System von Wörtern."),
    ("Wort", "Wörter", "das", "die", "Einheit der Sprache."),
    ("Frage", "Fragen", "die", "die", "Bitte um Information."),
    ("Antwort", "Antworten", "die", "die", "Reaktion auf eine Frage."),
    ("Problem", "Probleme", "das", "die", "Schwierige Situation."),
    ("Lösung", "Lösungen", "die", "die", "Weg aus einem Problem."),
    ("Idee", "Ideen", "die", "die", "Gedanke oder Plan."),
    ("Plan", "Pläne", "der", "die", "Vorbereitete Vorgehensweise."),
    ("Ziel", "Ziele", "das", "die", "Gewünschtes Ergebnis."),
    ("Weg", "Wege", "der", "die", "Route oder Methode."),
    ("Reise", "Reisen", "die", "die", "Fahrt in ein anderes Land."),
    ("Urlaub", "Urlaube", "der", "die", "Freie Zeit von der Arbeit."),
    ("Wetter", "—", "das", "—", "Zustand von Sonne und Regen."),
    ("Sonne", "Sonnen", "die", "die", "Heller Stern am Himmel."),
    ("Regen", "—", "der", "—", "Wasser aus den Wolken."),
    ("Schnee", "—", "der", "—", "Weiße Flocken im Winter."),
    ("Wind", "Winde", "der", "die", "Bewegte Luft."),
    ("Musik", "—", "die", "—", "Kunst aus Tönen."),
    ("Film", "Filme", "der", "die", "Bewegte Bildgeschichte."),
    ("Spiel", "Spiele", "das", "die", "Aktivität zum Vergnügen."),
    ("Sport", "Sportarten", "der", "die", "Körperliche Aktivität."),
    ("Ball", "Bälle", "der", "die", "Rundes Spielobjekt."),
    ("Team", "Teams", "das", "die", "Gruppe von Spielern."),
    ("Sieg", "Siege", "der", "die", "Gewinn eines Wettbewerbs."),
    ("Fehler", "Fehler", "der", "die", "Falsche Handlung."),
    ("Erfolg", "Erfolge", "der", "die", "Gutes Ergebnis."),
    ("Glück", "—", "das", "—", "Positive Zufallserfahrung."),
    ("Liebe", "—", "die", "—", "Starke Zuneigung."),
    ("Hoffnung", "Hoffnungen", "die", "die", "Wunsch nach Gutem."),
    ("Angst", "Ängste", "die", "die", "Gefühl der Furcht."),
    ("Freude", "Freuden", "die", "die", "Gefühl des Glücks."),
    ("Traum", "Träume", "der", "die", "Bilder im Schlaf."),
    ("Gedanke", "Gedanken", "der", "die", "Idee im Kopf."),
    ("Erinnerung", "Erinnerungen", "die", "die", "Bild aus der Vergangenheit."),
    ("Zukunft", "Zukunfte", "die", "die", "Kommende Zeit."),
    ("Vergangenheit", "Vergangenheiten", "die", "die", "Frühere Zeit."),
    ("Gegenwart", "Gegenwarten", "die", "die", "Jetzige Zeit."),
    ("Leben", "Leben", "das", "die", "Existenz eines Wesens."),
    ("Tod", "Tode", "der", "die", "Ende des Lebens."),
    ("Gesundheit", "—", "die", "—", "Guter Zustand des Körpers."),
    ("Krankheit", "Krankheiten", "die", "die", "Körperliche Störung."),
    ("Arzt", "Ärzte", "der", "die", "Mediziner für Patienten."),
    ("Krankenhaus", "Krankenhäuser", "das", "die", "Ort für Behandlung."),
    ("Medizin", "Medizinen", "die", "die", "Heilmittel."),
    ("Essen", "—", "das", "—", "Nahrung zum Verzehr."),
    ("Getränk", "Getränke", "das", "die", "Flüssigkeit zum Trinken."),
    ("Kaffee", "—", "der", "—", "Heißes braunes Getränk."),
    ("Tee", "Tees", "der", "die", "Heißes Getränk aus Blättern."),
    ("Bier", "Biere", "das", "die", "Alkoholisches Getränk."),
    ("Wein", "Weine", "der", "die", "Getränk aus Trauben."),
]
